// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows; // Add this line for Windows configuration
      // throw UnsupportedError(
      //   'DefaultFirebaseOptions have not been configured for windows - '
      //   'you can reconfigure this by running the FlutterFire CLI again.',
      // );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBayH3sL4kJeovRSv1XTxfMsZyRVuAMd9A',
    appId: '1:889858529798:web:fa3ecbb73eb906b8b68187',
    messagingSenderId: '889858529798',
    projectId: 'fyhaa-8b63a',
    authDomain: 'fyhaa-8b63a.firebaseapp.com',
    storageBucket: 'fyhaa-8b63a.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDlpKtAu43ZtymUvc1zRpyVVSteT9t8t70',
    appId: '1:889858529798:android:17e31445da794d25b68187',
    messagingSenderId: '889858529798',
    projectId: 'fyhaa-8b63a',
    storageBucket: 'fyhaa-8b63a.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCkfjTDnkZ3A4xqU_jNjb55Kj68OwPAmNg',
    appId: '1:889858529798:ios:2d5c3be49023ecd5b68187',
    messagingSenderId: '889858529798',
    projectId: 'fyhaa-8b63a',
    storageBucket: 'fyhaa-8b63a.appspot.com',
    iosClientId:
        '889858529798-tp433nac7rp81974cv3fvqo95fuc1957.apps.googleusercontent.com',
    iosBundleId: 'com.example.fyhaa',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCkfjTDnkZ3A4xqU_jNjb55Kj68OwPAmNg',
    appId: '1:889858529798:ios:1174816299992803b68187',
    messagingSenderId: '889858529798',
    projectId: 'fyhaa-8b63a',
    storageBucket: 'fyhaa-8b63a.appspot.com',
    iosClientId:
        '889858529798-83cik0ufm6upm9neu1h853b1pojlfl0s.apps.googleusercontent.com',
    iosBundleId: 'com.example.fyhaa.RunnerTests',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCkfjTDnkZ3A4xqU_jNjb55Kj68OwPAmNg',
    appId: '1:889858529798:ios:1174816299992803b68187',
    messagingSenderId: '889858529798',
    projectId: 'fyhaa-8b63a',
    // Add other necessary configuration options for Windows here.
  );
}
